// <auto-generated />
using System;
using Anemette.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anemette.Web.Data.Migreringer
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009081803_Start")]
    partial class Start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Anemette.Web.Data.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdgangskodeHash")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Brugernavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GammelHash")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GammelSalt")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Oprettet")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SidstLoggetInd")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Brugernavn")
                        .IsUnique();

                    b.ToTable("Administratorer", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Arrangement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("Pladser")
                        .HasColumnType("int");

                    b.Property<decimal?>("Pris")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sted")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Synlig")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Arrangementer", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Billede")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Indhold")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Indledning")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.Property<bool>("Synlig")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Udgivet")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Artikler", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Bog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Emne")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Forside")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Fremhaevet")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Lager")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oprettet")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Pris")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Sider")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Udgivelsesaar")
                        .HasColumnType("int");

                    b.Property<string>("Undertitel")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Boeger", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Indstilling", b =>
                {
                    b.Property<string>("Noegle")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Vaerdi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Noegle");

                    b.ToTable("Indstillinger", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Kontaktbesked", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Besked")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Emne")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Laest")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Oprettet")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kontaktbeskeder", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Ordre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Anonymiseret")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Besked")
                        .HasColumnType("longtext");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Oprettet")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Postnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Sendt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ordrer", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Ordrelinje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<int?>("BogId")
                        .HasColumnType("int");

                    b.Property<int>("OrdreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Stykpris")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BogId");

                    b.HasIndex("OrdreId");

                    b.ToTable("Ordrelinjer", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Side", b =>
                {
                    b.Property<string>("Noegle")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Indhold")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Opdateret")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Noegle");

                    b.ToTable("Sider", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Tilmelding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<int>("ArrangementId")
                        .HasColumnType("int");

                    b.Property<string>("Besked")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Oprettet")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ArrangementId");

                    b.ToTable("Tilmeldinger", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", (string)null);
                });

            modelBuilder.Entity("Anemette.Web.Data.Ordrelinje", b =>
                {
                    b.HasOne("Anemette.Web.Data.Bog", "Bog")
                        .WithMany()
                        .HasForeignKey("BogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anemette.Web.Data.Ordre", "Ordre")
                        .WithMany("Linjer")
                        .HasForeignKey("OrdreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bog");

                    b.Navigation("Ordre");
                });

            modelBuilder.Entity("Anemette.Web.Data.Tilmelding", b =>
                {
                    b.HasOne("Anemette.Web.Data.Arrangement", "Arrangement")
                        .WithMany("Tilmeldinger")
                        .HasForeignKey("ArrangementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrangement");
                });

            modelBuilder.Entity("Anemette.Web.Data.Arrangement", b =>
                {
                    b.Navigation("Tilmeldinger");
                });

            modelBuilder.Entity("Anemette.Web.Data.Ordre", b =>
                {
                    b.Navigation("Linjer");
                });
#pragma warning restore 612, 618
        }
    }
}
