//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anemette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArtikel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArtikel()
        {
            this.tblBilledes = new HashSet<tblBillede>();
        }
    
        public int ID { get; set; }
        public string ArtikelOverskrift { get; set; }
        public string ArtikelTekst { get; set; }
        public string ArtikelBannerBillede { get; set; }
        public string ArtikelManchetTekst { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBillede> tblBilledes { get; set; }
    }
}
