//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anemette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillede
    {
        public int ID { get; set; }
        public string BilledeFil { get; set; }
        public string BilledeAlternativTekst { get; set; }
        public string BilledeBeskrivelse { get; set; }
        public string BilledeOverskrift { get; set; }
        public Nullable<int> FK_Type { get; set; }
        public Nullable<int> FK_Artikel { get; set; }
        public Nullable<int> FK_Produkt { get; set; }
        public Nullable<int> FK_Event { get; set; }
        public Nullable<int> FK_Bestyrelse { get; set; }
        public Nullable<int> FK_Person { get; set; }
        public Nullable<int> FK_Sponsor { get; set; }
        public Nullable<int> FK_Side { get; set; }
    
        public virtual tblArtikel tblArtikel { get; set; }
        public virtual tblProdukt tblProdukt { get; set; }
        public virtual tblType tblType { get; set; }
        public virtual tblBestyrelse tblBestyrelse { get; set; }
        public virtual tblPerson tblPerson { get; set; }
        public virtual tblSide tblSide { get; set; }
        public virtual tblSponsor tblSponsor { get; set; }
        public virtual tblEvent tblEvent { get; set; }
    }
}
