//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anemette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBestyrelse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBestyrelse()
        {
            this.tblBilledes = new HashSet<tblBillede>();
        }
    
        public int ID { get; set; }
        public string MedlemsBillede { get; set; }
        public string MedlemsNavn { get; set; }
        public string MedlemsTitel { get; set; }
        public string MedlemsBeskrivelse { get; set; }
        public string MedlemsMail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBillede> tblBilledes { get; set; }
    }
}
