//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anemette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent()
        {
            this.tblBilledes = new HashSet<tblBillede>();
            this.tblTilmeldings = new HashSet<tblTilmelding>();
        }
    
        public int ID { get; set; }
        public string EventOverskrift { get; set; }
        public Nullable<System.DateTime> EventDato { get; set; }
        public string EventBeskrivelse { get; set; }
        public Nullable<int> EventPris { get; set; }
        public Nullable<int> EventPladser { get; set; }
        public Nullable<int> EventDistance { get; set; }
        public Nullable<int> FK_Region { get; set; }
        public Nullable<int> FK_Sponsor { get; set; }
        public Nullable<int> FK_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBillede> tblBilledes { get; set; }
        public virtual tblEventRegion tblEventRegion { get; set; }
        public virtual tblSponsor tblSponsor { get; set; }
        public virtual tblType tblType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTilmelding> tblTilmeldings { get; set; }
    }
}
