//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anemette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPerson()
        {
            this.tblNyhedsbrevs = new HashSet<tblNyhedsbrev>();
            this.tblSvars = new HashSet<tblSvar>();
            this.tblTilmeldings = new HashSet<tblTilmelding>();
            this.tblBilledes = new HashSet<tblBillede>();
        }
    
        public int ID { get; set; }
        public string NavnTilPerson { get; set; }
        public string TelefonnummerTilPerson { get; set; }
        public string EmailTilPerson { get; set; }
        public string BilledeAfPerson { get; set; }
        public string RSVP { get; set; }
        public string SamtykkeTilDenneListe { get; set; }
        public Nullable<int> FK_HvorKenderViPersonenFra { get; set; }
        public string MedlemsskabAfForetagsomheden { get; set; }
        public string BidragTilAuktionen { get; set; }
        public string BidragTilSneglebingo { get; set; }
        public string BidragTilForberedelse { get; set; }
        public Nullable<int> FK_TjansUnderEvent { get; set; }
        public string Salt { get; set; }
        public string HashetLink { get; set; }
        public Nullable<int> FK_BilletType { get; set; }
        public Nullable<System.DateTime> AlderAfPerson { get; set; }
        public Nullable<int> LoebeDistanceForPerson { get; set; }
        public Nullable<int> FK_Region_Hjemstavn { get; set; }
        public string AdresseTilPerson { get; set; }
        public Nullable<int> AntalGangePersonenHarBesogtSiden { get; set; }
    
        public virtual tblBillet tblBillet { get; set; }
        public virtual tblEventRegion tblEventRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNyhedsbrev> tblNyhedsbrevs { get; set; }
        public virtual tblSted tblSted { get; set; }
        public virtual tblTjan tblTjan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSvar> tblSvars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTilmelding> tblTilmeldings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBillede> tblBilledes { get; set; }
    }
}
