//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anemette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSide()
        {
            this.tblTags = new HashSet<tblTag>();
            this.tblBilledes = new HashSet<tblBillede>();
        }
    
        public int ID { get; set; }
        public string SideTitel { get; set; }
        public string SideBeskrivelse { get; set; }
        public Nullable<System.DateTime> SideOprettelsesDato { get; set; }
        public string SideLink { get; set; }
        public string SideBillede { get; set; }
        public Nullable<int> FK_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTag> tblTags { get; set; }
        public virtual tblType tblType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBillede> tblBilledes { get; set; }
    }
}
