//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anemette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSvar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSvar()
        {
            this.tblValgs = new HashSet<tblValg>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_Person { get; set; }
        public Nullable<int> FK_Spm { get; set; }
        public string Svar { get; set; }
    
        public virtual tblPerson tblPerson { get; set; }
        public virtual tblSpm tblSpm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblValg> tblValgs { get; set; }
    }
}
