//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anemette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTilmelding
    {
        public int ID { get; set; }
        public string TilmeldteEmail { get; set; }
        public Nullable<int> FK_Event { get; set; }
        public Nullable<int> FK_Person { get; set; }
    
        public virtual tblPerson tblPerson { get; set; }
        public virtual tblEvent tblEvent { get; set; }
    }
}
