//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anemette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValg
    {
        public int ID { get; set; }
        public string Valg { get; set; }
        public Nullable<int> FK_Spm { get; set; }
        public Nullable<int> FK_Svar_DetKorrekteSvar { get; set; }
    
        public virtual tblSpm tblSpm { get; set; }
        public virtual tblSvar tblSvar { get; set; }
    }
}
